// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6wZ-JIks1f4fJBMrK6az7w3LO6EqLD-c',
    appId: '1:446862193240:android:c5623719e640c95809502d',
    messagingSenderId: '446862193240',
    projectId: 'flowwise-c8189',
    storageBucket: 'flowwise-c8189.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBa-bk1B1u5K3-tzbZVHUhaSKRJN5J2pc',
    appId: '1:446862193240:web:1ded1e0e94556ff809502d',
    messagingSenderId: '446862193240',
    projectId: 'flowwise-c8189',
    authDomain: 'flowwise-c8189.firebaseapp.com',
    storageBucket: 'flowwise-c8189.firebasestorage.app',
    measurementId: 'G-ZVXWQMV94Q',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZn1NV_jEzxMBGPuyudYs4RPmRo6itSmw',
    appId: '1:446862193240:ios:a40eb0e642ca4c8509502d',
    messagingSenderId: '446862193240',
    projectId: 'flowwise-c8189',
    storageBucket: 'flowwise-c8189.firebasestorage.app',
    iosBundleId: 'com.example.flowwise',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZn1NV_jEzxMBGPuyudYs4RPmRo6itSmw',
    appId: '1:446862193240:ios:a40eb0e642ca4c8509502d',
    messagingSenderId: '446862193240',
    projectId: 'flowwise-c8189',
    storageBucket: 'flowwise-c8189.firebasestorage.app',
    iosBundleId: 'com.example.flowwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBa-bk1B1u5K3-tzbZVHUhaSKRJN5J2pc',
    appId: '1:446862193240:web:14119c5b2c2da3fd09502d',
    messagingSenderId: '446862193240',
    projectId: 'flowwise-c8189',
    authDomain: 'flowwise-c8189.firebaseapp.com',
    storageBucket: 'flowwise-c8189.firebasestorage.app',
    measurementId: 'G-H504LWDZ67',
  );
}
